services:
  binternet:
    container_name: binternet
    image: ghcr.io/ahwxorg/binternet:latest
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    expose:
      - "8080"  # Expose the port internally to other containers in the nginx network
    networks:
      - nginx  # Use the nginx network you created

networks:
  nginx:
    external: true  # Reference the external nginx network
