services:
  binternet:
    container_name: binternet
    restart: always
    image: ghcr.io/ahwxorg/binternet:latest
    expose:
      - "8080"
    networks:
      - nginx

networks:
  nginx:
    external: true
